language: python
env:
  - GITHUB_TOKEN=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
python:
  - "3.5"
install:
  - pip install requests
# command to run tests
script:
   - python -m unittest githubapitest.py